# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lony
tagline:          'The stuff I try'
url:              https://www.lony.in

paginate:         5

# Custom vars
version:          1.0.1

exclude: ['Rakefile', 'README']
