# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lony In
tagline:          'How do you get in alone'
description:      'Do we want to get in the weird place'
url:              http://dev.lony.in

author:
  name:           'Lony'
  email:            contact@lony.in

paginate:         1

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/poole/poole
